name: Ping Web Site

on:
  push:
    branches: [ master ]
  schedule: 
    - cron: 35 21 * * * 
  workflow_dispatch:
jobs:
  ping:

    runs-on: ubuntu-latest
    environment: 
      name: webhook
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Ping IP
      run: |
        sudo apt-get install -y tcptraceroute bc
        sudo chmod +x ./tcping
        sudo mv tcping /usr/local/bin/tcping
        tcping -x 5  mailla.eu.org 81
        tcping -x 5  www.baidu.com 
    - name: Ping IP
      env:
        WEBHOOK: ${{ secrets.WEBHOOK }}
      run: |
        sudo chmod +x domainping.sh
        ./domainping.sh
  
          
    
    
   
