name: Ping Web Site

on:
  push:
    branches: [ master ]
  schedule: 
    - cron: 35 21 * * * 
jobs:
  ping:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 14
    - name: Install dependencies
      run: dotnet tool install Web.Ping -g
    - name: init
      run: npm install
    - name: Ping www.zkea.net
      run: Web.Ping --host http://www.baidu.com
    - name: Get muzipiao.github.io response status code.
      run: |
           nslookup mailla.eu.org
    - name: Ping www.zkea.net
      run: nmap -p 81 mailla.eu.org
   
