name: Ping Web Site

on:
  push:
    branches: [ master ]
  schedule: 
    - cron: 35 21 * * * 
  workflow_dispatch:
jobs:
  ping:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Ping IP
      run: |
        sudo apt-get install -y tcptraceroute bc
        sudo wget  https://github.com/pili-book/PingWebSite/blob/master/tcping
        sudo chmod +x tcping
        sudo mv tcping /usr/local/bin/tcping
        tcping -x 5  mailla.eu.org 81
        tcping -x 5  lixiaohu.nom.za 81
        tcping -x 5  qinjiaxian.nom.za 81
        tcping -x 5  yiyeshu.nom.za 81
    
    
    
    
   
